const router = require('express').Router();
const path = require('path');
const { createOrder, verifyPayment } = require('../controller/order');


/**
 * @swagger
 * tags:
 *   name: Order
 *   description: API endpoints for customer orders and order payment verification
 */
//  create order
/**
 * @swagger
 * /api/v1/order/create-order:
 *   post:
 *     tags:
 *       - Order
 *     summary: Place an order
 *     description: Creates a customer order from selected products, generates an order payment reference, and initializes Korapay checkout
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - customerId
 *               - email
 *               - products
 *               - deliveryAddress
 *             properties:
 *               customerId:
 *                 type: string
 *                 description: Customer ID
 *                 example: 6855e0c8b7f5a2a0fbc12345
 *               email:
 *                 type: string
 *                 format: email
 *                 description: Customer email
 *                 example: johndoe@gmail.com
 *               deliveryAddress:
 *                 type: string
 *                 description: Customer delivery address
 *                 example: Lekki Phase 1, Lagos
 *               products:
 *                 type: array
 *                 description: List of ordered products
 *                 items:
 *                   type: object
 *                   properties:
 *                     productId:
 *                       type: string
 *                       description: Product ID
 *                       example: 6855ab23c8d9f12345678901
 *                     quantity:
 *                       type: integer
 *                       description: Quantity of product ordered
 *                       example: 2
 *     responses:
 *       201:
 *         description: Order created successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Order created successfully
 *                 data:
 *                   type: object
 *                   properties:
 *                     customerId:
 *                       type: string
 *                       example: 6855e0c8b7f5a2a0fbc12345
 *                     products:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           productId:
 *                             type: string
 *                             example: 6855ab23c8d9f12345678901
 *                           quantity:
 *                             type: integer
 *                             example: 2
 *                           price:
 *                             type: number
 *                             example: 125000
 *                     totalPrice:
 *                       type: number
 *                       example: 250000
 *                     reference:
 *                       type: string
 *                       description: Order payment reference generated by the server
 *                       example: ORDER-1779710000000-123456
 *                     checkoutUrl:
 *                       type: string
 *                       description: Korapay checkout URL
 *                       example: https://checkout.korapay.com/pay/example
 *                     paymentStatus:
 *                       type: string
 *                       enum: [pending, processing, paid, failed]
 *                       example: pending
 *                     orderStatus:
 *                       type: string
 *                       enum: [processing, shipped, delivered, cancelled]
 *                       example: processing
 *                     deliveryAddress:
 *                       type: string
 *                       example: Lekki Phase 1, Lagos
 *                 paymentLink:
 *                   type: string
 *                   description: Korapay checkout URL
 *                   example: https://checkout.korapay.com/pay/example
 *       400:
 *         description: Required order details are missing
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: customerId, email, products, and deliveryAddress are required
 *       404:
 *         description: Customer or product was not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Product not found
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Something went wrong
 */
router.post('/create-order', createOrder);
// Verify Payments
/**
 * @swagger
 * /api/v1/order/verify-payment:
 *   get:
 *     tags:
 *       - Order
 *     summary: Verify payment status
 *     description: Verifies an order payment through Korapay using the generated order reference and updates the order payment status
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: reference
 *         required: true
 *         description: Payment reference generated during checkout
 *         schema:
 *           type: string
 *           example: ORDER-1779710000000-123456
 *     responses:
 *       200:
 *         description: Payment verification successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Payment successful
 *                 status:
 *                   type: string
 *                   enum: [processing, paid, failed]
 *                   example: paid
 *       404:
 *         description: Order not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Order not found
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Something went wrong
 */
router.get('/verify-payment', verifyPayment);

module.exports = router;
